package gr.kremmydas.sugarscape.agents.rules.pollution;

import gr.kremmydas.sugarscape.agents.AgentChapter2_p50;
import repast.simphony.valueLayer.GridValueLayer;

public interface PollutionAbility {
	
	/**
	 * Returns the pollution generated by the agent 
	 * @param ls
	 * @return  {@link GridValueLayer}
	 */
	public int pollute(AgentChapter2_p50 owner);
	
	
}
