package repast.simphony.demos.sugarscape2.agents.abilities.agents;

import repast.simphony.demos.sugarscape2.agents.old.SugarAgent_ch2p50;
import repast.simphony.valueLayer.GridValueLayer;

public interface PollutionAbility {
	
	/**
	 * Returns the pollution generated by the agent 
	 * @param ls
	 * @return  {@link GridValueLayer}
	 */
	public int pollute(SugarAgent_ch2p50 owner);
	
	
}
